Repository JuliaPhysics/SolidStateDetectors.jl, pull requests merged in 2021-07, with the labels that each got.

#182 Update configuration file conversion script
  examples/example_primitive_files/Torus.yaml
  src/ConstructiveSolidGeometry/IO.jl
  src/ConstructiveSolidGeometry/Transformations.jl
  src/ConstructiveSolidGeometry/VolumePrimitives/Box.jl
  src/ConstructiveSolidGeometry/VolumePrimitives/Cone.jl
  src/ConstructiveSolidGeometry/VolumePrimitives/Ellipsoid.jl
  src/ConstructiveSolidGeometry/VolumePrimitives/RegularPrism.jl
  src/ConstructiveSolidGeometry/VolumePrimitives/Torus.jl
  test/update_config_file.jl
Labels: convenience

#184 Write documentation for v0.6 release
  docs/make.jl
  docs/src/assets/ADLChargeDriftModel.pdf
  docs/src/assets/CSGDifference.png
  docs/src/assets/CSGIntersection.png
  docs/src/assets/CSGUnion.png
  docs/src/index.md
  docs/src/man/IO.md
  docs/src/man/charge_drift.md
  docs/src/man/config_files.md
  docs/src/man/csg.md
  docs/src/man/electric_field.md
  docs/src/man/electric_fields.md
  docs/src/man/electric_potential.md
  docs/src/man/electric_potentials.md
  docs/src/man/primitives.jl
  docs/src/man/transformations.md
  docs/src/man/weighting_potentials.md
  examples/example_config_files/infinite_coaxial_capacitor.yaml
  examples/example_config_files/infinite_coaxial_capacitor_cartesian_coords.yaml
  examples/example_config_files/infinite_parallel_plate_capacitor.yaml
  examples/example_config_files/ivc_splitted_config/channels/01_PointContact.yaml
  examples/example_config_files/ivc_splitted_config/channels/02_Mantle.yaml
  examples/example_config_files/ivc_splitted_config/public_ivc_cryostat_config.yaml
  examples/example_config_files/minimum_detector_config.yaml
  examples/example_config_files/minimum_hexagon_config.yaml
  examples/example_config_files/public_CGD_config.yaml
  examples/example_config_files/public_CGD_config_cyl_grid.yaml
  examples/example_config_files/public_Coax_config.yaml
  examples/example_config_files/public_SegBEGe_config.yaml
  examples/example_config_files/public_coaxial_torus_config.yaml
  examples/example_config_files/public_ivc_config.yaml
  examples/example_config_files/public_spherical_detector_config.yaml
  examples/example_config_files/test_detector.yaml
  src/ChargeDensities/ConstantChargeDensity.jl
  src/ChargeDensities/CylindricalChargeDensity.jl
  src/ChargeDensities/LinearChargeDensity.jl
  src/ChargeDriftModels/VacuumModel.jl
  src/Config/Config.jl
  src/ConstructiveSolidGeometry/IO.jl
  src/ConstructiveSolidGeometry/Units.jl
  src/ImpurityDensities/ConstantImpurityDensity.jl
  src/ImpurityDensities/CylindricalImpurityDensity.jl
  src/ImpurityDensities/LinearImpurityDensity.jl
  src/MaterialProperties/MaterialProperties.jl
  src/PotentialSimulation/PotentialSimulationSetups/PotentialSimulationSetupRBCartesian3D.jl
  src/PotentialSimulation/PotentialSimulationSetups/PotentialSimulationSetupRBCylindrical.jl
  src/SolidStateDetector/Contacts.jl
  src/SolidStateDetector/SigGenInterface.jl
  src/SolidStateDetector/SolidStateDetector.jl
  src/World/World.jl
  test/update_config_file.jl
Labels: documentation

#187 Bugfix for `paint!`
  examples/example_config_files/infinite_coaxial_capacitor.yaml
  examples/example_config_files/infinite_coaxial_capacitor_cartesian_coords.yaml
  src/PotentialSimulation/Painting/Painting.jl
  src/Simulation/Simulation.jl
  src/SolidStateDetector/SigGenInterface.jl
  test/comparison_to_analytic_solutions.jl
  test/runtests.jl
Labels: bug
