Repository JuliaPhysics/SolidStateDetectors.jl, pull requests merged in 2021-08, with the labels that each got.

#195 Improvements and fixes in IO for v0.6
  src/Config/Config.jl
  src/ConstructiveSolidGeometry/IO.jl
  src/ElectricField/ElectricField.jl
  src/Grids/Grids.jl
  src/PlotRecipes/ElectricField.jl
  src/PlotRecipes/PotentialSimulationSetup.jl
  src/PlotRecipes/Potentials.jl
  src/PotentialSimulation/Painting/Painting.jl
  src/PotentialSimulation/PotentialSimulationSetups/PotentialSimulationSetupRBCartesian3D.jl
  src/PotentialSimulation/PotentialSimulationSetups/PotentialSimulationSetupRBCylindrical.jl
  src/PotentialSimulation/RedBlack/RedBlack.jl
  src/Simulation/Simulation.jl
  src/SolidStateDetector/Passive.jl
Labels: bug

#203 Speed-up in set `point_types`
  src/PotentialSimulation/PotentialSimulationSetups/PotentialSimulationSetupRBCartesian3D.jl
  src/PotentialSimulation/PotentialSimulationSetups/PotentialSimulationSetupRBCylindrical.jl
Labels: performance

#201 Improvements `ssd_write`/`ssd_read` and conversion `Simulation` <-> `NamedTuple`
  docs/src/man/IO.md
  examples/example_config_files/public_CGD_config.yaml
  examples/example_config_files/public_CGD_config_cyl_grid.yaml
  examples/example_config_files/public_coaxial_torus_config.yaml
  examples/example_config_files/public_ivc_config.yaml
  examples/example_config_files/public_spherical_detector_config.yaml
  examples/example_config_files/test_detector.yaml
  src/ConstructiveSolidGeometry/IO.jl
  src/IO/IO.jl
  src/IO/hdf5_specific.jl
  src/Simulation/Simulation.jl
  test/ConstructiveSolidGeometry/CSG_decomposition.jl
  test/ConstructiveSolidGeometry/CSG_test.jl
  test/runtests.jl
Labels: enhancement, notation, convenience, documentation

#205 Support `bulletize_PC` keyword in SigGen config files
  docs/src/tutorial_lit.jl
  src/IO/SigGenInterface.jl
Labels: enhancement, convenience
