Repository JuliaPhysics/SolidStateDetectors.jl, pull requests merged in 2024-12, with the labels that each got.

#440 Update documentation on charge densities
  docs/src/man/electric_potential.md
  src/Units.jl
Labels: documentation

#441 Minor update in painting algorithm for `CylindricalGrid`
  src/ConstructiveSolidGeometry/SurfacePrimitives/ConeMantle.jl
  src/ConstructiveSolidGeometry/SurfacePrimitives/TorusMantle.jl
  src/PotentialCalculation/Painting.jl
  test/test_real_detectors.jl
Labels: performance

#340 Run CI with four Julia threads active
  .github/workflows/Downgrade.yml
  .github/workflows/ci.yml
  src/Simulation/Simulation.jl
  test/Project.toml
  test/runtests.jl
  test/test_real_detectors.jl
Labels: help wanted

#446 Parse charge densities in units of Coulomb per volume
  examples/example_config_files/public_ivc_config.yaml
  examples/example_config_files/public_ivc_trapping_config.yaml
  src/ChargeDensities/ConstantChargeDensity.jl
  src/ChargeDensities/CylindricalChargeDensity.jl
  src/ChargeDensities/LinearChargeDensity.jl
  test/test_real_detectors.jl
Labels: bug

#370 Update to Documenter v1
  .github/workflows/ci.yml
  docs/Project.toml
  docs/make.jl
  src/ConstructiveSolidGeometry/CSG.jl
Labels: dependencies
