Repository JuliaPhysics/SolidStateDetectors.jl, pull requests merged in 2024-11, with the labels that each got.

#427 Update documentation regarding `LegendHDF5IO`
  docs/src/man/IO.md
  src/IO/IO.jl
  src/MCEventsProcessing/MCEventsProcessing.jl
Labels: documentation

#429 Bug fix in `parse_material` in `Geant4` extension
  ext/Geant4/io_gdml.jl
  test/Geant4.jl
Labels: bug, geant4

#428 Bug fix in `LegendHDF5IO` extension and restructure tests
  .gitignore
  Project.toml
  ext/SolidStateDetectorsLegendHDF5IOExt.jl
  test/ADLChargeDriftModel.jl
  test/IO.jl
  test/Project.toml
  test/runtests.jl
  test/test_analytic_solutions.jl
  test/test_charge_drift_models.jl
  test/test_geant4.jl
  test/test_gpu_backend.jl
  test/test_io.jl
  test/test_isochrone.jl
  test/test_real_detectors.jl
  test/test_utils.jl
Labels: bug

#433 SSD --> GDML parser: Choose smallest possible world
  ext/Geant4/io_gdml.jl
Labels: geant4

#430 Add bubble check when estimating the depletion voltage
  src/Simulation/DepletionVoltage.jl
  src/SolidStateDetector/SolidStateDetector.jl
  test/BEGe_01.yaml
  test/runtests.jl
  test/test_depletion.jl
Labels: bug, enhancement, convenience

#437 Adapt precision type of `G4JLApplication` to `Simulation`
  ext/SolidStateDetectorsGeant4Ext.jl
Labels: bug, geant4

#438 Fix constructor of `BoggsChargeTrappingModel`
  src/ChargeTrapping/ChargeTrapping.jl
  src/ConstructiveSolidGeometry/Units.jl
  test/test_charge_drift_models.jl
Labels: bug
