Repository JuliaPhysics/SolidStateDetectors.jl, pull requests merged in 2024-09, with the labels that each got.

#405 2D slice plotting
  docs/src/man/plotting.md
  docs/src/tutorials/complete_simulation_chain_IVC_lit.jl
  src/ConstructiveSolidGeometry/PointsAndVectors/PointsAndVectors.jl
  src/ConstructiveSolidGeometry/plotting/CSG/CSG.jl
  src/ConstructiveSolidGeometry/plotting/SurfacePrimitives/SurfacePrimitives.jl
  src/ConstructiveSolidGeometry/plotting/VolumePrimitives/VolumePrimitives.jl
  src/PlotRecipes/SolidStateDetector.jl
Labels: enhancement, convenience, new feature

#409 Add docstrings for exported functions related to the Geant4 extension
  ext/SolidStateDetectorsGeant4Ext.jl
  src/ChargeCloudModels/ParticleTypes.jl
  src/MCEventsProcessing/MCEventsProcessing.jl
Labels: documentation, geant4

#410 Add Geant4 extension
  .github/workflows/ci.yml
  .gitignore
  Project.toml
  docs/Project.toml
  docs/make.jl
  docs/src/tutorials/geant4_ssd_lit.jl
  ext/Geant4/g4jl_application.jl
  ext/Geant4/io_gdml.jl
  ext/Geant4/materials.xml
  ext/SolidStateDetectorsGeant4Ext.jl
  ext/SolidStateDetectorsLegendHDF5IOExt.jl
  src/ChargeCloudModels/ParticleTypes.jl
  src/ChargeClustering/ChargeClustering.jl
  src/ChargeStatistics/ChargeStatistics.jl
  src/ConstructiveSolidGeometry/IO.jl
  src/IO/hdf5_specific.jl
  src/MCEventsProcessing/MCEventsProcessing.jl
  src/MCEventsProcessing/table_utils.jl
  src/PlotRecipes/ChargeCloudModels.jl
  src/SolidStateDetectors.jl
  test/Geant4.jl
  test/runtests.jl
Labels: enhancement, new feature, documentation, dependencies, geant4

#411 Reintroduce `Requires` dependency for `LegendHDF5IO`
  .github/workflows/Downgrade.yml
  .github/workflows/ci.yml
  Project.toml
  ext/SolidStateDetectorsLegendHDF5IOExt.jl
  src/IO/IO.jl
  src/SolidStateDetectors.jl
  test/IO.jl
  test/Project.toml
  test/runtests.jl
Labels: dependencies

#412 Relax type constraints of config dictionaries
  Project.toml
  ext/Geant4/io_gdml.jl
  src/ChargeDensities/ChargeDensities.jl
  src/ChargeDensities/ConstantChargeDensity.jl
  src/ChargeDensities/CylindricalChargeDensity.jl
  src/ChargeDensities/LinearChargeDensity.jl
  src/ChargeDriftModels/ADLChargeDriftModel/TemperatureModels/BoltzmannModel.jl
  src/ChargeDriftModels/ADLChargeDriftModel/TemperatureModels/LinearModel.jl
  src/ChargeDriftModels/ADLChargeDriftModel/TemperatureModels/PowerLawModel.jl
  src/ChargeDriftModels/ADLChargeDriftModel/TemperatureModels/VacuumModel.jl
  src/ConstructiveSolidGeometry/CSG.jl
  src/ConstructiveSolidGeometry/ConstructiveSolidGeometry.jl
  src/ConstructiveSolidGeometry/IO.jl
  src/IO/IO.jl
  src/IO/ParseConfigFiles.jl
  src/IO/SigGenInterface.jl
  src/IO/Update.jl
  src/ImpurityDensities/ConstantImpurityDensity.jl
  src/ImpurityDensities/CylindricalImpurityDensity.jl
  src/ImpurityDensities/ImpurityDensities.jl
  src/ImpurityDensities/LinearImpurityDensity.jl
  src/Simulation/Simulation.jl
  src/SolidStateDetector/Contacts.jl
  src/SolidStateDetector/Passive.jl
  src/SolidStateDetector/Semiconductor.jl
  src/SolidStateDetector/SolidStateDetector.jl
  src/SolidStateDetector/VirtualVolumes.jl
  src/SolidStateDetectors.jl
  src/World/World.jl
  test/IO.jl
  test/Project.toml
Labels: dependencies
