Repository JuliaPhysics/SolidStateDetectors.jl, pull requests merged in 2025-05, with the labels that each got.

#481 Avoid deadlock concurrency in LegendHDF5IO extension
  docs/src/man/IO.md
  ext/SolidStateDetectorsLegendHDF5IOExt.jl
  src/IO/IO.jl
Labels: bug, convenience, dependencies

#487 Allow passing `validate_schema` to `Geant4.G4JLDetectorGDML`
  ext/SolidStateDetectorsGeant4Ext.jl
Labels: bug, convenience, geant4

#491 Corrections for impurity density models
  docs/src/man/electric_potential.md
  src/ImpurityDensities/BouleImpurityDensities/LinBouleImpurityDensity.jl
  src/ImpurityDensities/BouleImpurityDensities/LinExpBouleImpurityDensity.jl
  src/ImpurityDensities/BouleImpurityDensities/ParBouleImpurityDensity.jl
  src/ImpurityDensities/BouleImpurityDensities/ParExpBouleImpurityDensity.jl
  src/ImpurityDensities/ConstantImpurityDensity.jl
  src/ImpurityDensities/CylindricalImpurityDensity.jl
  src/ImpurityDensities/ImpurityDensities.jl
  src/ImpurityDensities/LinearImpurityDensity.jl
  src/SolidStateDetector/Semiconductor.jl
  test/BEGe_01.yaml
  test/test_boule_impurity_densities.jl
Labels: enhancement, convenience
